//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Values
    {
        public int activeValues_ID { get; set; }
        public string columnName { get; set; }
        public string programOutcomeAbbr { get; set; }
        public string activeStatus { get; set; }
        public int courseOutcomes_FK { get; set; }
    
        public virtual Course_Outcomes Course_Outcomes { get; set; }
    }
}
