//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Criteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment_Criteria()
        {
            this.Grading_Rubrics = new HashSet<Grading_Rubrics>();
        }
    
        public int ac_id { get; set; }
        public int syllabus_id_fk { get; set; }
        public byte[] criteria_name { get; set; }
        public byte[] highest_points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grading_Rubrics> Grading_Rubrics { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
