//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bibliography
    {
        public int bibliography_id { get; set; }
        public int syllabus_id_fk { get; set; }
        public int sources_fk { get; set; }
    
        public virtual Source Source { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
