//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_id { get; set; }
        public int course_fk { get; set; }
        public string callNumber { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public int year { get; set; }
    }
}
