//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Value_Attribute
    {
        public int coreValueAttrib_ID { get; set; }
        public int coreValue_FK { get; set; }
        public string description { get; set; }
    
        public virtual Core_Value Core_Value { get; set; }
    }
}
