//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Deliverable
    {
        public int courseDeliverables_ID { get; set; }
        public int courseOutcomeAddressed_FK { get; set; }
        public int syllabus_FK { get; set; }
        public string outputName { get; set; }
        public string output_description { get; set; }
        public string assessmentTypeA { get; set; }
        public string assessmentTypeB { get; set; }
    
        public virtual Course_Outcome_Addressed Course_Outcome_Addressed { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
