//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliverable
    {
        public int DeliverableId { get; set; }
        public int GroupId { get; set; }
        public string Status { get; set; }
        public string TeacherComment { get; set; }
        public string StudentComment { get; set; }
        public string DateSubmitted { get; set; }
    
        public virtual Grouping Grouping { get; set; }
    }
}
