//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grading_Rubrics
    {
        public int gradingRubrics_ID { get; set; }
        public int assessmentCriteria_FK { get; set; }
        public string rubricStatus { get; set; }
        public string points { get; set; }
        public string description { get; set; }
    
        public virtual Assessment_Criteria Assessment_Criteria { get; set; }
    }
}
