//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Discussion_Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Discussion_Entry()
        {
            this.Group_Discussion_Reply = new HashSet<Group_Discussion_Reply>();
        }
    
        public int group_discussion_entry_id { get; set; }
        public int group_id { get; set; }
        public int school_id { get; set; }
        public string post { get; set; }
        public string time { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Discussion_Reply> Group_Discussion_Reply { get; set; }
    }
}
