//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Here
    {
        public int grading_system1 { get; set; }
        public Nullable<int> syllabus_FK1 { get; set; }
        public string typeOfGrading1 { get; set; }
        public Nullable<int> weight1 { get; set; }
        public string requirementsName1 { get; set; }
    }
}
