//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learning_Plan
    {
        public int learning_ID { get; set; }
        public Nullable<int> courseOutcome_FK { get; set; }
        public int course_id_fk { get; set; }
        public int quarter_FK { get; set; }
        public int syllabus_FK { get; set; }
        public string learningOutcomeDesc { get; set; }
        public int hours { get; set; }
        public string topics { get; set; }
        public string teacherActivity { get; set; }
        public string learnerActivity { get; set; }
        public string assessmentActivity { get; set; }
    
        public virtual Quarter Quarter { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
