//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learning_Plan
    {
        public int learning_id { get; set; }
        public int co_id_fk { get; set; }
        public int course_id_fk { get; set; }
        public int quarter_id_fk { get; set; }
        public int syllabus_id_fk { get; set; }
        public string learning_outcome { get; set; }
        public string hours { get; set; }
        public string topics { get; set; }
        public string teacher_activity { get; set; }
        public string learner_activity { get; set; }
        public string assessment_activity { get; set; }
    
        public virtual Quarter Quarter { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
