//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int preference_id { get; set; }
        public int start_time { get; set; }
        public int end_time { get; set; }
        public string day { get; set; }
        public int user_id { get; set; }
    }
}
