//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_EO
    {
        public int peo_id { get; set; }
        public int core_value_id_fk { get; set; }
        public int syllabus_id_fk { get; set; }
        public string objective { get; set; }
    
        public virtual Core_Value Core_Value { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
