//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisions_Log
    {
        public int log_ID { get; set; }
        public int revision_id_fk { get; set; }
        public int who_revised { get; set; }
        public int who_next { get; set; }
    
        public virtual Revision Revision { get; set; }
    }
}
