//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software_Used
    {
        public int softwareUsed_ID { get; set; }
        public int course_FK { get; set; }
        public int syllabus_FK { get; set; }
        public string software { get; set; }
    
        public virtual Syllabu Syllabu { get; set; }
    }
}
