//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_in_offered_courses
    {
        public int students_in_offered_courses1 { get; set; }
        public int teacher_id { get; set; }
        public int school_id { get; set; }
        public string request_status { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual User User { get; set; }
    }
}
