//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic_Discussion_Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic_Discussion_Entry()
        {
            this.Topic_Discussion_Reply = new HashSet<Topic_Discussion_Reply>();
        }
    
        public int topic_discussion_entry_id { get; set; }
        public int topic_id { get; set; }
        public int user_id { get; set; }
        public string datetime { get; set; }
        public string topic_discussion_post { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic_Discussion_Reply> Topic_Discussion_Reply { get; set; }
    }
}
