//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic_Discussion_Reply
    {
        public int topic_discussion_reply_id { get; set; }
        public int topic_discussion_entry_id { get; set; }
        public int user_id { get; set; }
        public string time { get; set; }
        public string topic_discussion_reply_post { get; set; }
    
        public virtual Topic_Discussion_Entry Topic_Discussion_Entry { get; set; }
        public virtual User User { get; set; }
    }
}
