//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Groups = new HashSet<Group>();
            this.Group_Discussion_Entry = new HashSet<Group_Discussion_Entry>();
            this.Group_Discussion_Reply = new HashSet<Group_Discussion_Reply>();
            this.Students_in_offered_courses = new HashSet<Students_in_offered_courses>();
            this.Topic_Discussion_Entry = new HashSet<Topic_Discussion_Entry>();
            this.Users_In_Group = new HashSet<Users_In_Group>();
        }
    
        public int schoolId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string userType { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public Nullable<int> yearLevel { get; set; }
        public string gender { get; set; }
        public string birthday { get; set; }
        public string address { get; set; }
        public string guardian { get; set; }
        public string guardianAddress { get; set; }
        public string relationshipToGuardian { get; set; }
        public string contactNumber { get; set; }
        public string emergencyNumber { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Discussion_Entry> Group_Discussion_Entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Discussion_Reply> Group_Discussion_Reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_in_offered_courses> Students_in_offered_courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic_Discussion_Entry> Topic_Discussion_Entry { get; set; }
        public virtual Topic_Discussion_Reply Topic_Discussion_Reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_In_Group> Users_In_Group { get; set; }
    }
}
