//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIS_Syllabus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_In_Group
    {
        public int user_in_group_id { get; set; }
        public int school_id { get; set; }
        public int group_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
